/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EndpointsRouteImport } from './routes/endpoints'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV2TemplatesAnimeNumNameRouteImport } from './routes/api/v2/templates/anime.$num.$name'

const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsRoute = EndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2TemplatesAnimeNumNameRoute =
  ApiV2TemplatesAnimeNumNameRouteImport.update({
    id: '/api/v2/templates/anime/$num/$name',
    path: '/api/v2/templates/anime/$num/$name',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/endpoints': typeof EndpointsRoute
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/api/v2/templates/anime/$num/$name': typeof ApiV2TemplatesAnimeNumNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/endpoints': typeof EndpointsRoute
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/api/v2/templates/anime/$num/$name': typeof ApiV2TemplatesAnimeNumNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/endpoints': typeof EndpointsRoute
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/api/v2/templates/anime/$num/$name': typeof ApiV2TemplatesAnimeNumNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/endpoints'
    | '/login'
    | '/request-access'
    | '/api/v2/templates/anime/$num/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/endpoints'
    | '/login'
    | '/request-access'
    | '/api/v2/templates/anime/$num/$name'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/endpoints'
    | '/login'
    | '/request-access'
    | '/api/v2/templates/anime/$num/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EndpointsRoute: typeof EndpointsRoute
  LoginRoute: typeof LoginRoute
  RequestAccessRoute: typeof RequestAccessRoute
  ApiV2TemplatesAnimeNumNameRoute: typeof ApiV2TemplatesAnimeNumNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints': {
      id: '/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof EndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/templates/anime/$num/$name': {
      id: '/api/v2/templates/anime/$num/$name'
      path: '/api/v2/templates/anime/$num/$name'
      fullPath: '/api/v2/templates/anime/$num/$name'
      preLoaderRoute: typeof ApiV2TemplatesAnimeNumNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EndpointsRoute: EndpointsRoute,
  LoginRoute: LoginRoute,
  RequestAccessRoute: RequestAccessRoute,
  ApiV2TemplatesAnimeNumNameRoute: ApiV2TemplatesAnimeNumNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
